### ISSUE TITLE
IOS 17.3 issue RSD Address,port  获取为空

### ISSUE THREAD

**Issue by yachi666** [RManLuo/FakePosition#10]
> zhinan@zhinan-m1 FakePosition-master % sh change_ios_position.sh 34.210213988584904 108.8370305299759
> 未找到相关进程
> Command PID: 2752
> 
> Waiting for RSD Address and RSD Port...
> Command has finished
> RSD Address: 
> RSD Port: 
> 2024-02-01 12:20:52 zhinan-m1 pymobiledevice3.cli.mounter[2769] ERROR DeveloperDiskImage already mounted
> Latitude: 34.210213988584904
> Longitude: 108.8370305299759
> Usage: pymobiledevice3 developer dvt simulate-location set 
>            [OPTIONS] LATITUDE LONGITUDE
> Try 'pymobiledevice3 developer dvt simulate-location set -h' for help.
> 
> Error: Invalid value for '--rsd': '' is not a valid integer.
> change_ios_position.sh: line 73: kill: (2752) - No such process

@RManLuo 
尝试重新连接+重启都无效

**Comment by yachi666** [comment]
issue fix, after synchronizing the latest sh script

**Comment by vijaymuralidhara** [comment]
Sorry what do you mean by "synchronizing the latest sh script"?

**Comment by yachi666** [comment]
> Sorry what do you mean by "synchronizing the latest sh script"?

Please download the latest code~
