### ISSUE TITLE
How can I set several geo-location points

### ISSUE THREAD

**Issue by AndrewQAmobidev** [RManLuo/FakePosition#11]
The tool works well for my mac. The only issue is that when stopping the execution with an already set lat, long GPS point - the location changes back to the actual (real) GPS position. Actually, this is not an issue :)  
But is it possible to set the next lat, long values right after the first ones - so that I could create a route with points? Cause now I can only spoof the location and "stand" on that point without navigation to the new coordinate.
Or maybe if it is possible to set the route as a number of points for the execution?

Thank you!

**Comment by AndrewQAmobidev** [comment]
> The tool works well for my mac. The only issue is that when stopping the execution with an already set lat, long GPS point - the location changes back to the actual (real) GPS position. Actually, this is not an issue :) But is it possible to set the next lat, long values right after the first ones - so that I could create a route with points? Cause now I can only spoof the location and "stand" on that point without navigation to the new coordinate. Or maybe if it is possible to set the route as a number of points for the execution?
> 
> Thank you!

Oh, I've found the workaround - we can run the script in the new terminal without stopping the previous one. In such way, we can move from one point to another one, and repeat again for 3rd, 4th etc. points.

**Comment by RManLuo** [comment]
It is good to hear that my script can help. Just a few add-ups, you can create a script with predefined geo-location points for tracing. Subsequently, you can invoke my script by passing these location points as parameters to simulate a trace.
