### ISSUE TITLE
invalid after IOS 18.2

### ISSUE THREAD

**Issue by chensjtu** [RManLuo/FakePosition#16]
This script seems not take effect after IOS 18.2. Any suggestions? 👀

**Comment by RManLuo** [comment]
Run `python3 -m pip install -U pymobiledevice3` to update the package and try again.

**Comment by chensjtu** [comment]
yeah, I have updated, but fails. After several debugs, I finally found the point. The IOS 18.2 requires pymobiledevice3 working on python 3.13. So after renew python env and pymobiledevice3, it now works. Many thanks for the wonderful code~

**Comment by RManLuo** [comment]
Good to know that! Thanks for sharing your experience.
