### ISSUE TITLE
 好像一直无法读取RSD Address和RSD Port 

### ISSUE THREAD

**Issue by cutemanworking** [RManLuo/FakePosition#6]
在 Linux和Mac环境分别测试过，好像都是无法读取RSD Address和RSD Port, 显示都是空值， 然后出错。

**Comment by RManLuo** [comment]
可以检查是否本地有开启类似vpn之类的全局代理服务

**Comment by fjybiocs** [comment]
> 可以检查是否本地有开启类似vpn之类的全局代理服务

关闭了vpn，在WIFI设置中取消了代理之后，貌似还是一直无法获取

**Comment by RManLuo** [comment]
Should be fixed now 27346089de8d660990f5903b9dfb72b43f6df92f
